### PR TITLE
feat: Added multiline functionality

### PR DESCRIPTION
**Pull request by parsa-asgari**
Hi,
Hope you're doing well.

There was this requirement pertaining to having multi-line feedback texts in Streamlit-feedback. So I went ahead and made it possible as best as I could. I have replaced the InputField with a TextField to enable the textbox to be scrollable. Also, I have made sure to preserve the previous one-line textbox and ensure that this feature adds value to the current structure, not modify it.

Hope it adds some value to this already awesome package!

### CODE REVIEW

**Comment by jeffkayne** [comment]
Hello @parsa-asgari 

First thanks for this contrib, it's awesome!

To make it simpler for users who want to use this, I see there being a single parameter. Something like this:

```py
def streamlit_feedback(multiline_text_length=None):
    """
    multiline_text_length: Optional[int]
        If specified, a multiline text box will be configured with this as a maximum number of characters.
    """
```

Also, to reduce code complexity, could we use an if statement to treat this behaviour directly in `ThumbsWithQualiFeedback` and `FacesWithQualiFeedback`?

Many thanks!

**Comment by parsa-asgari** [comment]
Sure!

I'm glad that you have found the contribution valuable.

To be honest, I decided not to change your code due to the fact that I'm not fluent in JS or React. And about the parameter, you are indeed correct. The two parameters are redundant. Thanks for pointing out.

I'll try to incorporate your feedback into the contribution. 

Big Thanks!

**Comment by KylePancamo** [comment]
This would be a great feature. Being able to provide more than a single line of feedback would be awesome.

**Comment by parsa-asgari** [comment]
**Hi,** 
Sorry for the late response. I've been really busy lately.
I've modified the code based on your feedback. I hope it is now best aligned with the direction of your repository.

If there is anything, please let me know.

Thanks,
**Best Regards**

**Comment by jeffkayne** [comment]
hey @parsa-asgari 

LGTM! Thanks for this 🔥

**Pull request merged**
